name: Update release draft

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: Update draft release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
